export const emojiDict: Record<string, string> = {
  "😀": "mặt cười tươi",
  "😃": "mặt cười há miệng",
  "😄": "mặt cười há miệng và mắt cười",
  "😁": "mặt cười toe toét",
  "😆": "mặt cười nhắm mắt",
  "😅": "mặt cười toát mồ hôi",
  "😂": "cười ra nước mắt",
  "🤣": "cười lăn lộn",
  "🥲": "cười ra nước mắt",
  "😊": "mặt cười mỉm",
  "😇": "mặt cười thiên thần",
  "🙂": "mặt cười nhẹ",
  "🙃": "mặt lộn ngược",
  "😉": "chớp mắt",
  "😌": "nhẹ nhõm",
  "😍": "cười mắt trái tim",
  "🥰": "cười nhiều trái tim",
  "😘": "hôn mập mờ",
  "😗": "mặt hôn",
  "😙": "mặt hôn cười",
  "😚": "hôn nhắm mắt",
  "😋": "mặt thè lưỡi",
  "😛": "thè lưỡi",
  "😝": "thè lưỡi nhắm mắt",
  "😜": "thè lưỡi nháy mắt",
  "🤪": "điên rồ",
  "🤨": "nhướng mày",
  "🧐": "mặt kính lúp",
  "🤓": "mặt mọt sách",
  "😎": "mặt ngầu",
  "🥸": "cải trang",
  "🤩": "mặt mắt ngôi sao",
  "🥳": "chúc mừng",
  "😏": "cười nhếch mép",
  "😒": "không vui",
  "😞": "thất vọng",
  "😔": "buồn bã",
  "😟": "lo lắng",
  "😕": "bối rối",
  "🙁": "mặt buồn",
  "☹️": "cau mày",
  "😣": "chịu đựng",
  "😖": "lúng túng",
  "😫": "mệt mỏi",
  "😩": "kiệt sức",
  "🥺": "mặt nài nỉ",
  "😢": "khóc",
  "😭": "khóc lớn",
  "😮💨": "thở dài",
  "😤": "mặt hếch mũi tức giận",
  "😠": "giận dữ",
  "😡": "đỏ mặt giận dữ",
  "🤬": "chửi thề",
  "🤯": "đầu nổ tung",
  "😳": "đỏ mặt ngượng",
  "🥵": "nóng nực",
  "🥶": "lạnh buốt",
  "😱": "sợ hãi tột độ",
  "😨": "sợ hãi",
  "😰": "sợ toát mồ hôi",
  "😥": "buồn toát mồ hôi",
  "😓": "toát mồ hôi hột",
  "🤗": "mặt ôm",
  "🤔": "suy nghĩ",
  "🫣": "nhìn trộm",
  "🤭": "che miệng cười",
  "🤫": "suỵt",
  "🤥": "nói dối",
  "😶": "không mồm",
  "😶💨": "trong mây",
  "😐": "vô cảm",
  "😑": "mờ nhạt",
  "😬": "nhe răng",
  "🫨": "mặt rung",
  "🙄": "đảo mắt",
  "😯": "há miệng ngạc nhiên",
  "😦": "buồn há miệng",
  "😧": "đau khổ",
  "😮": "ngạc nhiên",
  "😲": "kinh ngạc",
  "🥱": "ngáp",
  "😴": "đang ngủ",
  "🤤": "chảy dãi",
  "😪": "ngái ngủ",
  "😵": "hoa mắt",
  "😵💫": "chóng mặt",
  "🤐": "kéo khóa miệng",
  "🥴": "say xỉn",
  "🤢": "buồn nôn",
  "🤮": "nôn mửa",
  "🤧": "hắt hơi",
  "😷": "đeo khẩu trang",
  "🤒": "ngậm nhiệt kế",
  "🤕": "quấn băng đầu",
  "🤑": "miệng tiền",
  "🤠": "đội mũ cao bồi",
  "😈": "quỷ cười",
  "👿": "quỷ giận",
  "👹": "yêu quái đỏ",
  "👺": "yêu quái mũi dài",
  "🤡": "mặt hề",
  "💩": "cục phân",
  "👻": "con ma",
  "💀": "đầu lâu",
  "☠️": "đầu lâu xương chéo",
  "👽": "người ngoài hành tinh",
  "👾": "quái vật",
  "🤖": "rô bốt",
  "👋": "vẫy tay",
  "👍": "like",
  "👎": "chê",
  "❤️": "trái tim đỏ",
  "💔": "trái tim tan vỡ",
  "🔥": "lửa",
  "✨": "lấp lánh"
};

export const translateEmojiToVietnamese = (text: string, skipEmoji: boolean): string => {
  if (skipEmoji) {
    // Regular expression to match emojis and remove them
    return text.replace(/[\u{1F300}-\u{1F64F}\u{1F680}-\u{1F6FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}\u{1F900}-\u{1F9FF}\u{1F1E0}-\u{1F1FF}]/gu, '');
  }

  let result = text;
  // Sort keys by length descending so that multi-character emojis are replaced first if any
  const sortedKeys = Object.keys(emojiDict).sort((a, b) => b.length - a.length);
  for (const emoji of sortedKeys) {
    if (result.includes(emoji)) {
      result = result.replaceAll(emoji, ` ${emojiDict[emoji]} `);
    }
  }
  return result.replace(/\s+/g, ' ').trim();
};
